# Generated by Django 5.0.11 on 2025-01-21 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('identificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('correo', models.CharField(max_length=30)),
                ('contrasena', models.CharField(max_length=130)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Automovil',
            fields=[
                ('id_auto', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.IntegerField()),
                ('marca', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('placa', models.CharField(max_length=10)),
                ('precio', models.IntegerField(default=0)),
                ('imagen', models.ImageField(upload_to='imagenes')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.categoria')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.estado')),
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.vendedor')),
            ],
        ),
    ]
